enum ProfileTypeEnumCode {
  SYSTEM_ADMINISTRATOR = 8,
  IN_HOUSE_DESIGNER = 4,
  DESIGN_PARTNER = 17,
  ASSOCIATE_STUDIO_MANAGER = 10,
  STUDIO_MANAGER = 11,
  STUDIO_MANAGER_DP = 3,
  CENTER_DELIVERY_HEAD = 14,
  CITY_DELIVERY_HEAD = 1,
  ALL_INDIA_BUSINESS_HEAD = 6,
  CEO = 9,
  CHM_EXECUTIVE = 16,
  CHM_MANAGER = 13,
  SURVEY_EXECUTIVE = 15,
  SURVEY_MANAGER = 2,
  THREE_D_DESIGNER_RENDERS = 19,
  THREE_D_DESIGNER_SHELL = 18,
  THREE_D_MANAGER = 7,
  FINANCE_EXECUTIVE = 5,
  FRANCHISE_OWNER = 12,
}

export { ProfileTypeEnumCode };
