enum SmartSheetCellValueEnum {

  CLIENT_NAME = "client name",
  CLIENT_ID = "client id",
  CLIENT_EMAIL = "client email",
  CLIENT_CONTACT = "client contact",
  PROPERTY_NAME = "property name",
  PROPERTY_ADDRESS = "property address",
  DESIGNER_NAME = "designer name",
  DESIGN_STUDIO = "design studio",
  SALES_OWNER = "sales owner",
  PROJECT_SIGNUP_VALUE = "project signup value",
  STATUS = "status",
  DESIGN_STAGE = "design stage",
  DESIGN_ITERATION = "design iteration",
  MATERIAL_SELECTION = "material selection",
  PREPARE_GFC = "prepare gfc (production drawings)",
  SEND_DWGS_GFC = "send dwgs for gfc checking",
  HANDOVER_DATE = "handover date",
  REVISED_HANDOVER_DATE = "revised handover date",
  PROJECT_MANAGER = "project manager",

  PROJECT_SIGNUP = "project signup",
  SITE_SURVEY = "site survey",
  KNOW_YOUR_CLIENT = "know your client (kyc)",
  FIRST_CUT_MEETING = "first cut meeting",
  DESIGN_FINALIZATION = "design finalization",
  REQUEST_PM_FOR_KICKOFF = "request pm for kickoff",
  KICKOFF_MEETING_AT_SITE = "kickoff meeting at site",
  DWG_REVISIONS = "dwg revisions completed",
  GFC_CHECKING = "gfc checking",
  DESIGN_SIGN_OFF = "design sign off",
  PROJECT_RECEIVED_FOR_PLANNING = "project received for planning",
  THIRTYFIVE_PAYMENT_CONFIRMATION = "35% payment confirmation",
  PRODUCTION = "production",
  READY_FOR_DISPATCH = "ready for dispatch",
  READY_FOR_HANDOVER = "ready for handover",
  HANDOVER = "handover",
  DESIGN_SIGN_OFF_PRESENTATION = "design sign off presentation",
  PENDING_HARDWARE_QC = "pending hardware qc",
  SITE_SURVEY_COMPLETE = "site survey complete",
  DESIGN_PRESENTATION = "design presentation",
  FOURTYFIVE_PAYMENT_CONFIRMATION = "45% payment confirmation",
  FIFTEEN_PAYMENT_CONFIRMATION = "15% payment confirmation",
}
export default SmartSheetCellValueEnum;
