enum SupportPalConcernTypeEnum {
    "Customer Dashboard",
    "3D Render",
    "Cancel the Project",
    "Clarification on Costing",
    "Delay compensation",
    "Delay in Design Phase",
    "Design Error",
    "Incorrect committment on Material",
    "Incorrect committment on Price",
    "Issue with design",
    "Issue with proposal",
    "Lack of Communication",
    "Lack of internal co-ordination",
    "Material Selection",
    "Not happy with team",
    "Partial refund",
    "Poor behaviour",
    "Project Timelines",
    "Refund",
    "Request for change in PM / Designer",
    "Site maintenance",
    "Discounts / EMI Scheme",
    "Dispatch delayed after payment",
    "Invoice Related",
    "Referral",
    "Clarity on Warranty",
    "Client Site damaged during installation",
    "Delay in Production & Installation",
    "Delay in sharing quote",
    "Design Error Found during Installation",
    "Execution Delay",
    "Execution Quality",
    "Issues with site works"
}

export default SupportPalConcernTypeEnum;
